- name: Install development tools
  hosts: dev

# Install python
- import_playbook: bootstrap-playbook.yml

# Setup our users
- import_playbook: users-playbook.yml

# Setup the dotfiles
- import_playbook: dotfiles-playbook.yml

# Install VS Code
- import_playbook: vscode-playbook.yml

# Install Docker
- import_playbook: docker-playbook.yml
