---
- name: Install vscode
  hosts:
    - all

  tasks:
    - name: vscode is configured
      import_role:
        name: vscode
      vars:
        vscode_extensions_user: cmihai
        vscode_extensions_install:
          - dhoeric.ansible-vault
          - ecmel.vscode-html-css
          - esbenp.prettier-vscode
          - foxundermoon.shell-format
          - haaaad.ansible
          - MikhailLuchkin.kubernetes-snip-and-pets
          - ms-azuretools.vscode-docker
          - ms-python.python
          - ms-vscode-remote.remote-ssh
          - ms-vscode-remote.remote-ssh-edit
          - PascalReitermann93.vscode-yaml-sort
          - redhat.vscode-yaml
          - rupisaini.vscode-ansible-linter
          - shd101wyy.markdown-preview-enhanced
          - streetsidesoftware.code-spell-checker
          - timonwong.ansible-autocomplete
          - timonwong.shellcheck
          - vscoss.vscode-ansible
          - webrender.synthwave-x-fluoromachine
          - yzhang.markdown-all-in-one
      tags: vscode
